### ISSUE TITLE
でふぉルトを東京からメルボルンにしてください

### ISSUE THREAD

**Issue by devhirodev** [MeetingTimeProject/MeetingTime#31]
@qahiro お願い :bow: 

## title

[00 仕様書.pdf](https://github.com/MeetingTimeProject/MeetingTime/files/299610/00.pdf)

**bold**

<img width="1280" alt="screen shot 2016-06-04 at 17 53 15" src="https://cloud.githubusercontent.com/assets/16112594/15809795/81256568-2bd2-11e6-81a0-9fe89fe70b79.png">

**Comment by qahiro** [comment]
@devhirodev わかりました 👿
