### ISSUE TITLE
メルボルンを東京に

### ISSUE THREAD

**Issue by devhirodev** [MeetingTimeProject/MeetingTime#61]
@qahiro 

お願いします :bow:
:octocat:

**Comment by qahiro** [comment]
ok
[00 仕様書.pdf](https://github.com/MeetingTimeProject/MeetingTime/files/336313/00.pdf)

![image](https://cloud.githubusercontent.com/assets/11475831/16404566/23e716a6-3d3b-11e6-8bed-f273a38a29dc.png)
